[theme]
primaryColor = "#4CAF50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[general]
favicon = "https://raw.githubusercontent.com/Victor1492Alvarez/Fuel_Cell-Battery_kpi-dashboard/main/dashboard_logo.png"
